name: run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: run tests
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04] # , windows-2019] TODO(katcipis): broken on windows for now x_x
        go: ["1.14", "1.15", "1.16", "1.17"]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup Go ${{matrix.go}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: running tests
        run: make test
